home/urls.py
from django.urls import path
from .views import UrlPage
from .views import VcardPage
from .views import WifiPage

urlpatterns = [
    path('wifi/', WifiPage.as_view()),
    path('vcard/', VcardPage.as_view()),
    path('', UrlPage.as_view()),
]

qrcodes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
]

home/models.py
from django.db import models

SECURITY_CHOICES = [
    ('Password', 'No password required'),
    ('WPA', 'WPA/WPA2'),
    ('WEP', 'WEP'),
]

# Create your models here.
class Url(models.Model):
    url = models.CharField(max_length=100)
    qrcode = models.CharField(max_length=1000)

class Vcard(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    address=models.CharField(max_length=100)
    country=models.CharField(max_length=100)

class Wifi(models.Model):
    ssid = models.CharField(max_length=100)
    security = models.CharField(max_length=100, choices=SECURITY_CHOICES)
    password = models.CharField(max_length=100)
    qrcode = models.CharField(max_length=1000)

home/forms.py
from django import forms
from home.models import Url
from home.models import Vcard
from home.models import Wifi
from home.models import SECURITY_CHOICES

import time


class UrlForm(forms.ModelForm):
    url = forms.CharField()
    
    class Meta:
        model = Url
        fields = ('url',)

class VCardForm(forms.ModelForm):
    name = forms.CharField()
    email = forms.CharField()
    phone = forms.CharField()
    address=forms.CharField()
    country=forms.CharField()
 
    class Meta:
        model = Vcard
        fields = ('name','email','phone','address','country')


class WifiForm(forms.ModelForm):
    ssid = forms.CharField(max_length=20)
    security = forms.CharField(widget=forms.Select(choices=SECURITY_CHOICES))
    password = forms.CharField(widget=forms.PasswordInput(), required=False)
 
    class Meta:
        model = Wifi
        fields = ('ssid','security','password')

def save_form(form):
    form.save()
    time.sleep(0.2)
    

home/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.core.files.storage import FileSystemStorage
from django.db import models

from home.forms import UrlForm
from home.forms import VCardForm
from home.forms import WifiForm
from home.forms import save_form
from home.generate_qr_codes import url_qr
from home.generate_qr_codes import wifi_qr
from home.generate_qr_codes import vcard_qr

import requests
import threading


# Create your views here.
class UrlPage(TemplateView, models.Model):
    template_name = 'url.html'
    
    def get(self, request):
        form = UrlForm()
        return render(request, self.template_name, {'form': form})
    
    def post(self,request):
        form = UrlForm(request.POST)
        url_thread = threading.Thread(target=save_form, args=(form,))
        if form.is_valid():
            values = {'url': form.cleaned_data['url']}
            url_thread.start()
            args = url_qr(values)
            
            return render(request, self.template_name, args)
         
        return render(request, self.template_name, {'form': form})


class VcardPage(TemplateView, models.Model):
    template_name='vcard.html'

    def get(self, request):
        form = VCardForm()
        return render(request, self.template_name, {'form': form})
    
    def post(self,request):
        fields = ['address', 'email', 'name', 'phone', 'country']
        
        if request.POST['action'] == 'upload':
            myfile = request.FILES['myfile']
            fs = FileSystemStorage()
            filename = fs.save(myfile.name, myfile)
            
            try:
                with open(filename, 'r') as f:
                    text = self.process_vcard_file(f)
                    data = {fields[i]: text[i].split(':')[1] for i in range(5)}
                    form = VCardForm(initial = data)     
                return render(request, self.template_name, {'form': form})
            except Exception: 
                if not myfile.name.endswith('.vcf'):
                    return render(request, self.template_name, {'form': VCardForm(), 'error': 'FileType not valid'})
                else:
                    return render(request, self.template_name, {'form': VCardForm(), 'error': 'Unkown error'})
        elif request.POST['action'] == 'generate':
            form = VCardForm(request.POST)
            vcard_thread = threading.Thread(target=save_form, args=(form,))

            if form.is_valid():
                values = {fields[i]:form.cleaned_data[fields[i]] for i in range(5)}
                vcard_thread.start()
                args = vcard_qr(values)
                return render(request, self.template_name, args)
            return render(request, self.template_name, {'form': form})
    
    def process_vcard_file(self, f):
        text = f.read()
        text = text.splitlines()
        del text[:2], text[-1]
        text[0] = text[0].replace('\\', '').replace(';', ' ')
        country = text[0].split('   ')[1]
        text[0] = text[0].split('   ')[0]
        text.append('Country:' + country)
        return text
    
class WifiPage(TemplateView, models.Model):
    template_name='wifi.html'

    def get(self, request):
        form = WifiForm(initial={'security': ''})
        return render(request, self.template_name, {'form': form})

    def post(self,request):
        form = WifiForm(request.POST)
        wifi_thread = threading.Thread(target=save_form, args=(form,))
        if form.is_valid():
            values = {
                'ssid': form.cleaned_data['ssid'],
                'security': form.cleaned_data['security'],
                'password': form.cleaned_data['password']
                }
            wifi_thread.start()
            #generate qrcode
            args = wifi_qr(values)
            
            return render(request, self.template_name, args)
        
        return render(request, self.template_name, {'form': form})

home/templates/index.html
<h1>Generate QRCodes</h1>
{% extends "nav.html" %}
    
{% block body %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type='submit'>Generate QR Code</button>
        {{text}}
    </form>
    <img src="{{qrcode}}">
        
</div>
{% endblock %} 

home/templates/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://code.jquery.com/jquery-3.4.0.slim.js" integrity="sha256-milezx5lakrZu0OP9b2QWFy1ft/UEUK6NH1Jqz8hUhQ=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>Generate QRCodes</title>
</head>
<body>
    <div class='container' style="margin-top: 50px">
        <h1 style="text-align: center; font-weight: bold">Generate QRCodes</h1>
        {% block nav %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light" style="border: 1px solid grey; box-shadow: 0px 0px 20px 1px black; background-color: #17a2b8 !important; font-size: x-large; font-family: sans-serif; font-weight: bold">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="/" style="color: white" onmouseover="this.style.color='black'"  onmouseout="this.style.color='white'">URL</a>
                    <a class="nav-item nav-link" href="/vcard" style="color: white" onmouseover="this.style.color='black'"  onmouseout="this.style.color='white'">VCard</a>
                    <a class="nav-item nav-link" href="/wifi" style="color: white" onmouseover="this.style.color='black'"  onmouseout="this.style.color='white'">WiFi</a>
                </div>
            </div>
        </nav>
        {% endblock %}
        
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

home/templates/url.html
{% extends "nav.html" %}
    
{% block body %}

    <div class="container row" style="height: 400px; margin: 0px; border-bottom: 1px solid grey;">
        <div class="col-sm-4 text-center my-auto">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-success" type='submit'>Generate QR Code</button>
            </form>
        </div>
        <div class="col-sm-4 text-center my-auto">
            <img src="{{qrcode}}" style="width: 200px">
        </div>
        <div class="col-sm-4 text-center my-auto">

            <ol style = "list-style-type: none">
                {% if qrcode %}<li style="margin-top: 5px"><a class="btn btn-info" style="width: 200px" href='{{qrcode}}' Download='urlqr.png'>Download as PNG</a> </li>{% endif %}
                {% if qrcode %}<li style="margin-top: 5px"><a class="btn btn-info" style="width: 200px" href='{{qrcodesvg}}' Download='urlqr.svg'>Download as SVG</a> </li>{% endif %}
                {% if qrcode %}<li style="margin-top: 5px"><a class="btn btn-info" style="width: 200px" href='{{qrcodeeps}}' Download='urlqr.eps'>Download as EPS</a> </li>{% endif %}
            </ol>
        </div>
    </div>

{% endblock %} 

home/templates/vcard.html
{% extends "nav.html" %}
    
{% block body %}

    <div class="container row" style="height: 400px; margin: 0px; border-bottom: 1px solid grey;">
        <div class="col-sm-4 text-center my-auto">
            <form method="post" >
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-success" type='submit' name="action" value="generate">Generate QR Code</button>
            </form>

            <form method="post" enctype="multipart/form-data" class="col-xs-12 text-center">
                {% csrf_token %}
                File: <input name="myfile" required type="file">
                <input class="btn btn-success" name="action" required type="submit" value="upload">
            </form>
        </div>

        <div class="col-sm-4 text-center my-auto">
            <img src="{{qrcode}}"  style="width: 200px">
        </div>

        <div class="col-sm-4 text-center my-auto">

                <ol style = "list-style-type: none">
                    {% if qrcode %}<li style="margin-top: 5px"><a class="btn btn-info" style="width: 200px" href='{{qrcode}}' download='vcardqr.png'>Download as PNG</a></li> {% endif %}
                    {% if qrcode %}<li style="margin-top: 5px"><a class="btn btn-info" style="width: 200px" href='{{qrcodesvg}}' download='vcardqr.svg'>Download SVG</a></li> {% endif %}
                    {% if qrcode %}<li style="margin-top: 5px"><a class="btn btn-info" style="width: 200px" href='{{qrcodeeps}}' download='vcardqr.eps'>Download as EPS</a></li> {% endif %}
                    {% if qrcode %}<li style="margin-top: 5px"><a class="btn btn-info" style="width: 200px" href='{{vcard}}' download='vcard.vcf' >Download as VCard File</a></li> {% endif %}
                </ol>
        </div>
    </div>
    <div class="col-sm-4 text-center my-auto">
            <p>{{error}}</p>
    </div>

{% endblock %} 

home/templates/wifi.html
{% extends "nav.html" %}
    
{% block body %}
    <div class="container row" style="height: 400px; margin: 0px; border-bottom: 1px solid grey;">
        <div class="col-sm-4 text-center my-auto">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-success my-auto" type='submit'>Generate QR Code</button>
            </form>
        </div>

        <div class="col-sm-4 text-center my-auto">
            <img src="{{qrcode}}"  style="width: 200px">
        </div>

        <div class="col-sm-4 text-center my-auto">

                <ol style = "list-style-type: none">
                        {% if qrcode %}<li style="margin-top: 5px"><a class="btn btn-info" style="width: 200px" href='{{qrcode}}' download='wifiqr.png'>Download as PNG</a> </li>{% endif %}
                        {% if qrcode %}<li style="margin-top: 5px"><a class="btn btn-info" style="width: 200px" href='{{qrcodesvg}}' donwload='wifiqr.svg'>Download SVG</a> </li>{% endif %}
                        {% if qrcode %}<li style="margin-top: 5px"><a class="btn btn-info" style="width: 200px" href='{{qrcodeeps}}' download='wifiqr.eps'>Download as EPS</a> </li>{% endif %}
                </ol>
        </div>
    </div>



<script>
    var password_field = $('#id_password');
    password_field.prop('disabled', true);
    
    $("#id_security").change(function() {
        if ($(this).val() === 'WPA' || $(this).val() === 'WEP') {
            password_field.prop('disabled', false);
        } else {
            password_field.prop('disabled', true);
        }
    });
</script>
{% endblock %} 